pub struct Definition {
    pub word: &'static str,
    pub part_of_speech: &'static str,
    pub definition: &'static str,
    pub example: &'static str,
    pub register: &'static str,
}

pub fn sample_definitions() -> Vec<Definition> {
    vec![
        Definition { word: "the", part_of_speech: "definite article", definition: "Used to refer to something specific or previously mentioned.", example: "The cat sat on the mat.", register: "conversational" },
        Definition { word: "be", part_of_speech: "verb", definition: "To exist, live, or have a state of being.", example: "To be or not to be, that is the question.", register: "literary" },
        Definition { word: "and", part_of_speech: "conjunction", definition: "Used to connect words or clauses.", example: "Apples and oranges are fruits.", register: "conversational" },
        Definition { word: "of", part_of_speech: "preposition", definition: "Expressing a relationship between two things.", example: "The color of the sky.", register: "formal" },
        Definition { word: "a", part_of_speech: "indefinite article", definition: "One; a single quantity or unit.", example: "A book on the table.", register: "conversational" },
        Definition { word: "in", part_of_speech: "preposition", definition: "Inside; within.", example: "He walked in the room.", register: "conversational" },
        Definition { word: "to", part_of_speech: "preposition", definition: "Motion or direction towards.", example: "She walked to the store.", register: "conversational" },
        Definition { word: "have", part_of_speech: "verb", definition: "To possess, own, or hold.", example: "I have a car.", register: "conversational" },
        Definition { word: "it", part_of_speech: "pronoun", definition: "Used to refer to a thing previously mentioned.", example: "It is raining today.", register: "conversational" },
        Definition { word: "i", part_of_speech: "pronoun", definition: "The speaker or writer.", example: "I need a coffee.", register: "conversational" },
        Definition { word: "that", part_of_speech: "demonstrative pronoun", definition: "Used to identify a specific thing.", example: "That is my book.", register: "conversational" },
        Definition { word: "for", part_of_speech: "preposition", definition: "Expressing purpose or intended use.", example: "He left for the market.", register: "conversational" },
        Definition { word: "you", part_of_speech: "pronoun", definition: "The person being addressed.", example: "You are kind.", register: "conversational" },
        Definition { word: "he", part_of_speech: "pronoun", definition: "A male person previously mentioned.", example: "He is my friend.", register: "conversational" },
        Definition { word: "with", part_of_speech: "preposition", definition: "Accompanied by; together.", example: "I went with my family.", register: "conversational" },
        Definition { word: "on", part_of_speech: "preposition", definition: "Located upon a surface.", example: "The book is on the table.", register: "conversational" },
        Definition { word: "do", part_of_speech: "verb", definition: "To perform or execute an action.", example: "I do my homework every day.", register: "conversational" },
        Definition { word: "say", part_of_speech: "verb", definition: "To utter words or speak.", example: "He said hello to everyone.", register: "conversational" },
        Definition { word: "this", part_of_speech: "pronoun", definition: "Used to identify something near the speaker.", example: "This is my house.", register: "conversational" },
        Definition { word: "they", part_of_speech: "pronoun", definition: "More than one person or thing.", example: "They are students at the university.", register: "conversational" },
        Definition { word: "at", part_of_speech: "preposition", definition: "Indicating a location or time.", example: "Meet me at the station.", register: "conversational" },
        Definition { word: "but", part_of_speech: "conjunction", definition: "Used to introduce a contrast.", example: "I like tea but not coffee.", register: "conversational" },
        Definition { word: "we", part_of_speech: "pronoun", definition: "The speaker and others.", example: "We are going to the park.", register: "conversational" },
        Definition { word: "his", part_of_speech: "possessive pronoun", definition: "Belonging to or associated with a male.", example: "His car is parked outside.", register: "conversational" },
        Definition { word: "from", part_of_speech: "preposition", definition: "Indicating the source or origin.", example: "She is from Brazil.", register: "conversational" },
        Definition { word: "not", part_of_speech: "adverb", definition: "Used to form the negative.", example: "I am not going.", register: "conversational" },
        Definition { word: "or", part_of_speech: "conjunction", definition: "Used to link alternatives.", example: "Coffee or tea?", register: "conversational" },
        Definition { word: "by", part_of_speech: "preposition", definition: "Indicating the agent or means.", example: "Written by Shakespeare.", register: "literary" },
        Definition { word: "as", part_of_speech: "conjunction", definition: "While or in the role of.", example: "As I was saying, it's important.", register: "conversational" },
        Definition { word: "what", part_of_speech: "interrogative pronoun", definition: "Asking for information.", example: "What is your name?", register: "conversational" },
        Definition { word: "go", part_of_speech: "verb", definition: "To move or travel.", example: "I go to work by bus.", register: "conversational" },
        Definition { word: "their", part_of_speech: "possessive pronoun", definition: "Belonging to them.", example: "Their house is beautiful.", register: "conversational" },
        Definition { word: "can", part_of_speech: "modal verb", definition: "To be able to.", example: "I can swim very well.", register: "conversational" },
        Definition { word: "who", part_of_speech: "interrogative pronoun", definition: "What person or people.", example: "Who is at the door?", register: "conversational" },
        Definition { word: "get", part_of_speech: "verb", definition: "To obtain or receive.", example: "I need to get some milk.", register: "conversational" },
        Definition { word: "if", part_of_speech: "conjunction", definition: "Introducing a conditional clause.", example: "If it rains, we will stay home.", register: "conversational" },
        Definition { word: "would", part_of_speech: "modal verb", definition: "Expressing a conditional or polite request.", example: "I would like some water.", register: "formal" },
        Definition { word: "her", part_of_speech: "possessive pronoun", definition: "Belonging to a female.", example: "Her dress is elegant.", register: "conversational" },
        Definition { word: "all", part_of_speech: "determiner", definition: "The whole quantity or number.", example: "All students must attend.", register: "formal" },
        Definition { word: "my", part_of_speech: "possessive pronoun", definition: "Belonging to me.", example: "My phone is new.", register: "conversational" },
        Definition { word: "make", part_of_speech: "verb", definition: "To create or produce something.", example: "She makes jewelry by hand.", register: "conversational" },
        Definition { word: "about", part_of_speech: "preposition", definition: "On the subject of; approximately.", example: "Tell me about your trip.", register: "conversational" },
        Definition { word: "know", part_of_speech: "verb", definition: "To be aware of or have information.", example: "I know the answer.", register: "conversational" },
        Definition { word: "will", part_of_speech: "modal verb", definition: "Expressing future tense.", example: "I will call you tomorrow.", register: "conversational" },
        Definition { word: "up", part_of_speech: "adverb", definition: "Toward a higher position.", example: "Look up at the stars.", register: "conversational" },
        Definition { word: "one", part_of_speech: "number", definition: "The first cardinal number.", example: "One apple is enough.", register: "conversational" },
        Definition { word: "time", part_of_speech: "noun", definition: "The indefinite continued progress of existence.", example: "Time flies when you're having fun.", register: "literary" },
        Definition { word: "there", part_of_speech: "adverb", definition: "In or at that place.", example: "Put it over there.", register: "conversational" },
        Definition { word: "year", part_of_speech: "noun", definition: "The period of 365 days.", example: "Next year I will travel.", register: "conversational" },
        Definition { word: "so", part_of_speech: "conjunction", definition: "Therefore; consequently.", example: "It was late, so I went home.", register: "conversational" },
        Definition { word: "think", part_of_speech: "verb", definition: "To have a belief or opinion.", example: "I think it's a good idea.", register: "conversational" },
        Definition { word: "when", part_of_speech: "adverb", definition: "At what time.", example: "When will you arrive?", register: "conversational" },
        Definition { word: "which", part_of_speech: "relative pronoun", definition: "What particular one.", example: "Which color do you prefer?", register: "conversational" },
        Definition { word: "them", part_of_speech: "pronoun", definition: "Used to refer to people or things.", example: "Give them the books.", register: "conversational" },
        Definition { word: "some", part_of_speech: "determiner", definition: "An unspecified amount or number.", example: "I need some help.", register: "conversational" },
        Definition { word: "me", part_of_speech: "pronoun", definition: "Used to refer to oneself.", example: "Give me a moment.", register: "conversational" },
        Definition { word: "people", part_of_speech: "noun", definition: "Human beings in general.", example: "People are kind here.", register: "conversational" },
        Definition { word: "take", part_of_speech: "verb", definition: "To lay hold of or carry away.", example: "Take an umbrella with you.", register: "conversational" },
        Definition { word: "out", part_of_speech: "adverb", definition: "Away from the inside.", example: "Go out and play.", register: "conversational" },
        Definition { word: "into", part_of_speech: "preposition", definition: "Expressing movement inside.", example: "She walked into the room.", register: "conversational" },
        Definition { word: "just", part_of_speech: "adverb", definition: "Exactly or only.", example: "I just arrived.", register: "conversational" },
        Definition { word: "see", part_of_speech: "verb", definition: "To perceive with the eyes.", example: "I can see the mountains.", register: "conversational" },
        Definition { word: "him", part_of_speech: "pronoun", definition: "Used to refer to a male.", example: "I saw him yesterday.", register: "conversational" },
        Definition { word: "your", part_of_speech: "possessive pronoun", definition: "Belonging to you.", example: "Your bag is on the chair.", register: "conversational" },
        Definition { word: "come", part_of_speech: "verb", definition: "To move toward the speaker.", example: "Come here, please.", register: "conversational" },
        Definition { word: "could", part_of_speech: "modal verb", definition: "Past tense of can; expressing possibility.", example: "I could help you if you want.", register: "conversational" },
        Definition { word: "now", part_of_speech: "adverb", definition: "At the present moment.", example: "Do it now.", register: "conversational" },
        Definition { word: "than", part_of_speech: "conjunction", definition: "Used in comparisons.", example: "She is taller than me.", register: "conversational" },
        Definition { word: "like", part_of_speech: "preposition", definition: "Similar to.", example: "It tastes like chicken.", register: "conversational" },
        Definition { word: "other", part_of_speech: "adjective", definition: "Different or additional.", example: "The other book is better.", register: "conversational" },
        Definition { word: "how", part_of_speech: "adverb", definition: "In what manner or way.", example: "How do you do that?", register: "conversational" },
        Definition { word: "then", part_of_speech: "adverb", definition: "At that time; next.", example: "First eat, then go out.", register: "conversational" },
        Definition { word: "its", part_of_speech: "possessive pronoun", definition: "Belonging to it.", example: "The dog wagged its tail.", register: "conversational" },
        Definition { word: "our", part_of_speech: "possessive pronoun", definition: "Belonging to us.", example: "Our team won the game.", register: "conversational" },
        Definition { word: "two", part_of_speech: "number", definition: "The second cardinal number.", example: "Two cups of coffee, please.", register: "conversational" },
        Definition { word: "more", part_of_speech: "determiner", definition: "A greater amount.", example: "I need more time.", register: "conversational" },
        Definition { word: "these", part_of_speech: "demonstrative pronoun", definition: "Plural of this.", example: "These are my books.", register: "conversational" },
        Definition { word: "want", part_of_speech: "verb", definition: "To have a desire for.", example: "I want a new phone.", register: "conversational" },
        Definition { word: "way", part_of_speech: "noun", definition: "A method or path.", example: "Show me the way.", register: "conversational" },
        Definition { word: "look", part_of_speech: "verb", definition: "To direct the eyes.", example: "Look at that sunset!", register: "conversational" },
        Definition { word: "first", part_of_speech: "adjective", definition: "Coming before all others.", example: "She was first in line.", register: "conversational" },
        Definition { word: "also", part_of_speech: "adverb", definition: "In addition; too.", example: "I also like chocolate.", register: "conversational" },
        Definition { word: "new", part_of_speech: "adjective", definition: "Not existing before; recently made.", example: "I bought a new car.", register: "conversational" },
        Definition { word: "because", part_of_speech: "conjunction", definition: "For the reason that.", example: "I stayed home because it was raining.", register: "conversational" },
        Definition { word: "day", part_of_speech: "noun", definition: "A 24-hour period.", example: "Have a nice day!", register: "conversational" },
        Definition { word: "use", part_of_speech: "verb", definition: "To employ for a purpose.", example: "Use a fork to eat.", register: "conversational" },
        Definition { word: "man", part_of_speech: "noun", definition: "An adult male human.", example: "The man was reading a book.", register: "conversational" },
        Definition { word: "find", part_of_speech: "verb", definition: "To discover or locate.", example: "I need to find my keys.", register: "conversational" },
        Definition { word: "here", part_of_speech: "adverb", definition: "In this place.", example: "Come here and sit down.", register: "conversational" },
        Definition { word: "thing", part_of_speech: "noun", definition: "An object or item.", example: "What is that thing?", register: "conversational" },
        Definition { word: "give", part_of_speech: "verb", definition: "To freely hand over.", example: "Give me the remote.", register: "conversational" },
        Definition { word: "many", part_of_speech: "determiner", definition: "A large number of.", example: "Many people attended.", register: "conversational" },
        Definition { word: "well", part_of_speech: "adverb", definition: "In a good manner.", example: "She sings well.", register: "conversational" },
        Definition { word: "only", part_of_speech: "adverb", definition: "No more than; solely.", example: "Only one cookie left.", register: "conversational" },
        Definition { word: "those", part_of_speech: "demonstrative pronoun", definition: "Plural of that.", example: "Those are expensive.", register: "conversational" },
        Definition { word: "tell", part_of_speech: "verb", definition: "To communicate information.", example: "Tell me a story.", register: "conversational" },
        Definition { word: "very", part_of_speech: "adverb", definition: "To a high degree.", example: "It's very cold outside.", register: "conversational" },
        Definition { word: "even", part_of_speech: "adverb", definition: "Used to emphasize something surprising.", example: "Even the dog was tired.", register: "conversational" },
        Definition { word: "back", part_of_speech: "noun", definition: "The rear part of something.", example: "He sat in the back of the car.", register: "conversational" },
        Definition { word: "good", part_of_speech: "adjective", definition: "Of a high quality or standard.", example: "That's a good idea.", register: "conversational" },
        Definition { word: "woman", part_of_speech: "noun", definition: "An adult female human.", example: "The woman smiled warmly.", register: "conversational" },
        Definition { word: "through", part_of_speech: "preposition", definition: "Moving in one side and out another.", example: "We walked through the forest.", register: "conversational" },
        Definition { word: "life", part_of_speech: "noun", definition: "The condition of being alive.", example: "Life is beautiful.", register: "literary" },
        Definition { word: "child", part_of_speech: "noun", definition: "A young human being.", example: "The child was playing in the park.", register: "conversational" },
        Definition { word: "work", part_of_speech: "noun", definition: "Activity involving effort.", example: "I have work to do.", register: "conversational" },
        Definition { word: "down", part_of_speech: "adverb", definition: "Toward a lower position.", example: "Sit down, please.", register: "conversational" },
        Definition { word: "may", part_of_speech: "modal verb", definition: "Expressing permission or possibility.", example: "May I come in?", register: "formal" },
        Definition { word: "after", part_of_speech: "preposition", definition: "Later in time than.", example: "After dinner, we watched a movie.", register: "conversational" },
        Definition { word: "should", part_of_speech: "modal verb", definition: "Expressing obligation or expectation.", example: "You should apologize.", register: "conversational" },
        Definition { word: "call", part_of_speech: "verb", definition: "To cry out or contact by phone.", example: "Call me when you arrive.", register: "conversational" },
        Definition { word: "world", part_of_speech: "noun", definition: "The earth and all its inhabitants.", example: "She traveled around the world.", register: "conversational" },
        Definition { word: "over", part_of_speech: "preposition", definition: "Above or on top of.", example: "A bird flew over the house.", register: "conversational" },
        Definition { word: "school", part_of_speech: "noun", definition: "An institution for educating children.", example: "The school opens at 8 AM.", register: "conversational" },
        Definition { word: "still", part_of_speech: "adverb", definition: "Continuing until now.", example: "I still love you.", register: "conversational" },
        Definition { word: "try", part_of_speech: "verb", definition: "To make an effort or attempt.", example: "Try your best.", register: "conversational" },
        Definition { word: "last", part_of_speech: "adjective", definition: "Coming after all others.", example: "This is the last piece.", register: "conversational" },
        Definition { word: "ask", part_of_speech: "verb", definition: "To inquire or request.", example: "Ask a question.", register: "conversational" },
        Definition { word: "need", part_of_speech: "verb", definition: "To require something essential.", example: "I need water.", register: "conversational" },
        Definition { word: "too", part_of_speech: "adverb", definition: "To an excessive degree.", example: "It's too hot today.", register: "conversational" },
        Definition { word: "feel", part_of_speech: "verb", definition: "To experience an emotion or sensation.", example: "I feel happy.", register: "conversational" },
        Definition { word: "three", part_of_speech: "number", definition: "The third cardinal number.", example: "Three birds sat on the fence.", register: "conversational" },
        Definition { word: "state", part_of_speech: "noun", definition: "A political entity or condition.", example: "The state passed a new law.", register: "formal" },
        Definition { word: "never", part_of_speech: "adverb", definition: "At no time in the past or future.", example: "Never give up.", register: "conversational" },
        Definition { word: "become", part_of_speech: "verb", definition: "To begin to be something.", example: "She became a doctor.", register: "conversational" },
        Definition { word: "between", part_of_speech: "preposition", definition: "In the space separating two things.", example: "Between the two trees.", register: "conversational" },
        Definition { word: "high", part_of_speech: "adjective", definition: "Of great vertical extent.", example: "The mountain is very high.", register: "conversational" },
        Definition { word: "really", part_of_speech: "adverb", definition: "In actual fact; truly.", example: "I really like this song.", register: "conversational" },
        Definition { word: "something", part_of_speech: "pronoun", definition: "An unspecified thing.", example: "Something smells good.", register: "conversational" },
        Definition { word: "most", part_of_speech: "determiner", definition: "The greatest in amount.", example: "Most people agree.", register: "conversational" },
        Definition { word: "another", part_of_speech: "determiner", definition: "One more; additional.", example: "Can I have another one?", register: "conversational" },
        Definition { word: "much", part_of_speech: "determiner", definition: "A large amount of.", example: "Much effort was needed.", register: "conversational" },
        Definition { word: "family", part_of_speech: "noun", definition: "A group of related people.", example: "My family is very supportive.", register: "conversational" },
        Definition { word: "own", part_of_speech: "adjective", definition: "Belonging to oneself.", example: "I have my own room.", register: "conversational" },
        Definition { word: "old", part_of_speech: "adjective", definition: "Having existed for a long time.", example: "This is an old building.", register: "conversational" },
        Definition { word: "while", part_of_speech: "conjunction", definition: "During the time that.", example: "While I was sleeping, it snowed.", register: "conversational" },
        Definition { word: "mean", part_of_speech: "verb", definition: "To intend to convey.", example: "What does this word mean?", register: "conversational" },
        Definition { word: "keep", part_of_speech: "verb", definition: "To continue to have or hold.", example: "Keep the change.", register: "conversational" },
        Definition { word: "student", part_of_speech: "noun", definition: "A person who studies.", example: "The student read quietly.", register: "conversational" },
        Definition { word: "why", part_of_speech: "adverb", definition: "For what reason.", example: "Why did you leave?", register: "conversational" },
        Definition { word: "let", part_of_speech: "verb", definition: "To allow or permit.", example: "Let me help you.", register: "conversational" },
        Definition { word: "great", part_of_speech: "adjective", definition: "Of a size or extent considerably above average.", example: "That's a great idea!", register: "conversational" },
        Definition { word: "same", part_of_speech: "adjective", definition: "Identical; not different.", example: "We have the same car.", register: "conversational" },
        Definition { word: "big", part_of_speech: "adjective", definition: "Of considerable size.", example: "A big house on the hill.", register: "conversational" },
        Definition { word: "group", part_of_speech: "noun", definition: "A number of people or things together.", example: "A group of students waited.", register: "conversational" },
        Definition { word: "begin", part_of_speech: "verb", definition: "To start something.", example: "Let's begin the lesson.", register: "conversational" },
        Definition { word: "seem", part_of_speech: "verb", definition: "To give an impression of being.", example: "It seems like rain.", register: "conversational" },
        Definition { word: "country", part_of_speech: "noun", definition: "A nation or territory.", example: "France is a beautiful country.", register: "conversational" },
        Definition { word: "help", part_of_speech: "verb", definition: "To assist or aid.", example: "Can you help me?", register: "conversational" },
        Definition { word: "talk", part_of_speech: "verb", definition: "To speak or converse.", example: "Let's talk about it.", register: "conversational" },
        Definition { word: "where", part_of_speech: "adverb", definition: "In what place.", example: "Where is the station?", register: "conversational" },
        Definition { word: "turn", part_of_speech: "verb", definition: "To change direction.", example: "Turn left at the corner.", register: "conversational" },
        Definition { word: "problem", part_of_speech: "noun", definition: "A matter or situation causing difficulty.", example: "We need to solve this problem.", register: "conversational" },
        Definition { word: "every", part_of_speech: "determiner", definition: "Each individual member of a set.", example: "Every student passed the test.", register: "conversational" },
        Definition { word: "start", part_of_speech: "verb", definition: "To begin or commence.", example: "Start the engine.", register: "conversational" },
        Definition { word: "might", part_of_speech: "modal verb", definition: "Expressing possibility.", example: "It might rain later.", register: "conversational" },
        Definition { word: "american", part_of_speech: "adjective", definition: "Relating to the United States.", example: "She speaks with an American accent.", register: "conversational" },
        Definition { word: "show", part_of_speech: "verb", definition: "To display or demonstrate.", example: "Show me what you made.", register: "conversational" },
        Definition { word: "part", part_of_speech: "noun", definition: "A piece or segment of something.", example: "This is an important part.", register: "conversational" },
        Definition { word: "long", part_of_speech: "adjective", definition: "Of extended length or duration.", example: "It was a long journey.", register: "conversational" },
        Definition { word: "little", part_of_speech: "adjective", definition: "Small in size or amount.", example: "A little bird sang.", register: "conversational" },
        Definition { word: "right", part_of_speech: "adjective", definition: "Morally correct or directionally opposite of left.", example: "Turn right at the light.", register: "conversational" },
        Definition { word: "put", part_of_speech: "verb", definition: "To place in a position.", example: "Put the keys on the table.", register: "conversational" },
        Definition { word: "home", part_of_speech: "noun", definition: "The place where one lives.", example: "Home is where the heart is.", register: "literary" },
        Definition { word: "number", part_of_speech: "noun", definition: "An arithmetical value.", example: "Seven is my lucky number.", register: "conversational" },
        Definition { word: "write", part_of_speech: "verb", definition: "To compose text.", example: "Write a letter to your friend.", register: "conversational" },
        Definition { word: "yes", part_of_speech: "interjection", definition: "Affirmative answer.", example: "Yes, I agree.", register: "conversational" },
        Definition { word: "follow", part_of_speech: "verb", definition: "To come after or go along.", example: "Follow me.", register: "conversational" },
        Definition { word: "change", part_of_speech: "verb", definition: "To make or become different.", example: "Change is inevitable.", register: "literary" },
        Definition { word: "play", part_of_speech: "verb", definition: "To engage in an activity for fun.", example: "Children play in the park.", register: "conversational" },
        Definition { word: "study", part_of_speech: "verb", definition: "To learn about a subject.", example: "I study English every day.", register: "conversational" },
        Definition { word: "each", part_of_speech: "determiner", definition: "Every one of two or more.", example: "Each student has a book.", register: "conversational" },
        Definition { word: "book", part_of_speech: "noun", definition: "A written work for reading.", example: "I am reading a good book.", register: "conversational" },
        Definition { word: "eye", part_of_speech: "noun", definition: "The organ of sight.", example: "She has beautiful eyes.", register: "conversational" },
        Definition { word: "run", part_of_speech: "verb", definition: "To move quickly on foot.", example: "He runs every morning.", register: "conversational" },
        Definition { word: "important", part_of_speech: "adjective", definition: "Of great significance.", example: "This is very important.", register: "conversational" },
        Definition { word: "city", part_of_speech: "noun", definition: "A large town.", example: "New York is a big city.", register: "conversational" },
        Definition { word: "plan", part_of_speech: "noun", definition: "A detailed proposal.", example: "We made a plan.", register: "conversational" },
        Definition { word: "notice", part_of_speech: "verb", definition: "To observe or become aware of.", example: "Did you notice the change?", register: "conversational" },
        Definition { word: "idea", part_of_speech: "noun", definition: "A thought or suggestion.", example: "That's a great idea!", register: "conversational" },
        Definition { word: "above", part_of_speech: "preposition", definition: "In a higher position.", example: "A plane flew above us.", register: "conversational" },
        Definition { word: "hard", part_of_speech: "adjective", definition: "Solid or difficult.", example: "The exam was hard.", register: "conversational" },
        Definition { word: "close", part_of_speech: "verb", definition: "To shut or bring together.", example: "Close the door, please.", register: "conversational" },
        Definition { word: "open", part_of_speech: "verb", definition: "To move to an unlocked position.", example: "Open the window.", register: "conversational" },
        Definition { word: "learn", part_of_speech: "verb", definition: "To gain knowledge or skill.", example: "Children learn quickly.", register: "conversational" },
        Definition { word: "live", part_of_speech: "verb", definition: "To remain alive or reside.", example: "I live in a small town.", register: "conversational" },
        Definition { word: "story", part_of_speech: "noun", definition: "A narrative or account.", example: "Tell me a story.", register: "conversational" },
        Definition { word: "young", part_of_speech: "adjective", definition: "In an early stage of life.", example: "A young tree grew in the garden.", register: "conversational" },
        Definition { word: "success", part_of_speech: "noun", definition: "The achievement of a goal.", example: "Hard work leads to success.", register: "conversational" },
        Definition { word: "believe", part_of_speech: "verb", definition: "To accept as true.", example: "I believe in you.", register: "conversational" },
        Definition { word: "enough", part_of_speech: "determiner", definition: "As much as is necessary.", example: "That's enough food for everyone.", register: "conversational" },
        Definition { word: "almost", part_of_speech: "adverb", definition: "Not quite; very nearly.", example: "We are almost there.", register: "conversational" },
        Definition { word: "able", part_of_speech: "adjective", definition: "Having the power or skill.", example: "I am able to help.", register: "conversational" },
        Definition { word: "against", part_of_speech: "preposition", definition: "In opposition to.", example: "He leaned against the wall.", register: "conversational" },
        Definition { word: "certain", part_of_speech: "adjective", definition: "Known for sure; established.", example: "Are you certain about that?", register: "conversational" },
        Definition { word: "morning", part_of_speech: "noun", definition: "The early part of the day.", example: "Good morning! Did you sleep well?", register: "conversational" },
        Definition { word: "head", part_of_speech: "noun", definition: "The upper part of the body.", example: "He nodded his head.", register: "conversational" },
        Definition { word: "move", part_of_speech: "verb", definition: "To change position or location.", example: "Move your chair closer.", register: "conversational" },
        Definition { word: "stand", part_of_speech: "verb", definition: "To be in an upright position.", example: "Stand up straight.", register: "conversational" },
        Definition { word: "true", part_of_speech: "adjective", definition: "In accordance with reality.", example: "Is it true that you're moving?", register: "conversational" },
        Definition { word: "power", part_of_speech: "noun", definition: "The ability or capacity to do something.", example: "Knowledge is power.", register: "literary" },
        Definition { word: "easy", part_of_speech: "adjective", definition: "Achieved without great effort.", example: "This test was easy.", register: "conversational" },
        Definition { word: "night", part_of_speech: "noun", definition: "The period of darkness in 24 hours.", example: "Good night, sleep well.", register: "conversational" },
        Definition { word: "body", part_of_speech: "noun", definition: "The physical structure of a person or animal.", example: "Regular exercise keeps the body healthy.", register: "conversational" },
        Definition { word: "understand", part_of_speech: "verb", definition: "To comprehend the meaning of something.", example: "I understand the instructions now.", register: "conversational" },
        Definition { word: "meet", part_of_speech: "verb", definition: "To come into the presence of.", example: "Nice to meet you!", register: "conversational" },
        Definition { word: "office", part_of_speech: "noun", definition: "A room for professional work.", example: "She works in an office.", register: "conversational" },
        Definition { word: "mind", part_of_speech: "noun", definition: "The faculty of consciousness and thought.", example: "Use your mind to solve problems.", register: "conversational" },
        Definition { word: "friend", part_of_speech: "noun", definition: "A person with whom one has a bond.", example: "She is my best friend.", register: "conversational" },
        Definition { word: "face", part_of_speech: "noun", definition: "The front part of the head.", example: "He had a smile on his face.", register: "conversational" },
        Definition { word: "place", part_of_speech: "noun", definition: "A particular position or location.", example: "This is a beautiful place.", register: "conversational" },
        Definition { word: "week", part_of_speech: "noun", definition: "A period of seven days.", example: "See you next week!", register: "conversational" },
        Definition { word: "point", part_of_speech: "noun", definition: "A particular moment or detail.", example: "Good point!", register: "conversational" },
        Definition { word: "small", part_of_speech: "adjective", definition: "Of limited size.", example: "A small cat sat on the step.", register: "conversational" },
        Definition { word: "house", part_of_speech: "noun", definition: "A building for human habitation.", example: "The house has a red door.", register: "conversational" },
        Definition { word: "next", part_of_speech: "adjective", definition: "Coming immediately after.", example: "The next train arrives at 5 PM.", register: "conversational" },
        Definition { word: "business", part_of_speech: "noun", definition: "Commercial activity or trade.", example: "He runs a small business.", register: "formal" },
        Definition { word: "question", part_of_speech: "noun", definition: "A sentence seeking information.", example: "Do you have a question?", register: "conversational" },
        Definition { word: "read", part_of_speech: "verb", definition: "To look at and understand written text.", example: "I love to read books.", register: "conversational" },
        Definition { word: "mother", part_of_speech: "noun", definition: "A female parent.", example: "My mother makes the best cookies.", register: "conversational" },
        Definition { word: "answer", part_of_speech: "noun", definition: "A reply to a question.", example: "The answer is correct.", register: "conversational" },
        Definition { word: "end", part_of_speech: "noun", definition: "The final part of something.", example: "The end of the movie was surprising.", register: "conversational" },
        Definition { word: "government", part_of_speech: "noun", definition: "The governing body of a nation.", example: "The government passed a new law.", register: "formal" },
        Definition { word: "letter", part_of_speech: "noun", definition: "A written message or a character of the alphabet.", example: "I wrote a letter to my grandmother.", register: "conversational" },
        Definition { word: "public", part_of_speech: "adjective", definition: "Open to all people.", example: "The park is public space.", register: "formal" },
        Definition { word: "full", part_of_speech: "adjective", definition: "Containing as much as possible.", example: "The glass is full of water.", register: "conversational" },
        Definition { word: "father", part_of_speech: "noun", definition: "A male parent.", example: "My father taught me to ride a bike.", register: "conversational" },
        Definition { word: "company", part_of_speech: "noun", definition: "A commercial business.", example: "She works for a tech company.", register: "conversational" },
        Definition { word: "hear", part_of_speech: "verb", definition: "To perceive sound with the ear.", example: "Can you hear the music?", register: "conversational" },
        Definition { word: "girl", part_of_speech: "noun", definition: "A female child.", example: "The girl laughed with joy.", register: "conversational" },
        Definition { word: "boy", part_of_speech: "noun", definition: "A male child.", example: "The boy played with his dog.", register: "conversational" },
        Definition { word: "always", part_of_speech: "adverb", definition: "At all times; forever.", example: "I will always love you.", register: "conversational" },
        Definition { word: "name", part_of_speech: "noun", definition: "A word by which someone or something is known.", example: "My name is John.", register: "conversational" },
        Definition { word: "side", part_of_speech: "noun", definition: "A position to the left or right.", example: "The store is on the other side of the street.", register: "conversational" },
        Definition { word: "far", part_of_speech: "adverb", definition: "At a great distance.", example: "How far is the airport?", register: "conversational" },
        Definition { word: "water", part_of_speech: "noun", definition: "A clear liquid essential for life.", example: "Drink more water every day.", register: "conversational" },
        Definition { word: "must", part_of_speech: "modal verb", definition: "Expressing necessity or obligation.", example: "You must finish your homework.", register: "conversational" },
        Definition { word: "large", part_of_speech: "adjective", definition: "Of great size.", example: "A large dog ran across the yard.", register: "conversational" },
        Definition { word: "fact", part_of_speech: "noun", definition: "Something known to be true.", example: "In fact, I was just thinking that.", register: "conversational" },
        Definition { word: "often", part_of_speech: "adverb", definition: "Frequently; many times.", example: "I often go for a walk after dinner.", register: "conversational" },
        Definition { word: "kind", part_of_speech: "noun", definition: "A group of things with similar characteristics.", example: "What kind of music do you like?", register: "conversational" },
        Definition { word: "rather", part_of_speech: "adverb", definition: "Preferentially; more willingly.", example: "I would rather stay home.", register: "conversational" },
        Definition { word: "along", part_of_speech: "preposition", definition: "Moving in a constant direction.", example: "Walk along the beach.", register: "conversational" },
        Definition { word: "person", part_of_speech: "noun", definition: "An individual human being.", example: "She is a kind person.", register: "conversational" },
        Definition { word: "door", part_of_speech: "noun", definition: "A movable barrier for an entrance.", example: "Please close the door.", register: "conversational" },
        Definition { word: "hope", part_of_speech: "verb", definition: "To wish for something with confidence.", example: "I hope you feel better soon.", register: "conversational" },
        Definition { word: "continue", part_of_speech: "verb", definition: "To carry on with something.", example: "Please continue with your work.", register: "conversational" },
        Definition { word: "love", part_of_speech: "noun", definition: "Intense affection and care.", example: "Love makes the world go round.", register: "literary" },
        Definition { word: "cause", part_of_speech: "noun", definition: "A reason or motive.", example: "What was the cause of the accident?", register: "conversational" },
        Definition { word: "second", part_of_speech: "noun", definition: "A unit of time.", example: "Wait a second, please.", register: "conversational" },
        Definition { word: "money", part_of_speech: "noun", definition: "A medium of exchange.", example: "Money doesn't buy happiness.", register: "literary" },
        Definition { word: "else", part_of_speech: "adverb", definition: "In addition; different.", example: "What else do you need?", register: "conversational" },
        Definition { word: "special", part_of_speech: "adjective", definition: "Better or greater than usual.", example: "Today is a special day.", register: "conversational" },
        Definition { word: "class", part_of_speech: "noun", definition: "A group of students taught together.", example: "The class starts at 9 AM.", register: "conversational" },
        Definition { word: "real", part_of_speech: "adjective", definition: "Genuine or actual.", example: "Is this real gold?", register: "conversational" },
        Definition { word: "check", part_of_speech: "verb", definition: "To examine or verify.", example: "Check your work before submitting.", register: "conversational" },
        Definition { word: "line", part_of_speech: "noun", definition: "A straight mark or queue.", example: "Wait in line please.", register: "conversational" },
        Definition { word: "speak", part_of_speech: "verb", definition: "To say words; talk.", example: "Please speak more slowly.", register: "conversational" },
        Definition { word: "example", part_of_speech: "noun", definition: "A thing serving as a model.", example: "Can you give me an example?", register: "conversational" },
        Definition { word: "food", part_of_speech: "noun", definition: "Any substance consumed for nutrition.", example: "The food here is delicious.", register: "conversational" },
        Definition { word: "teacher", part_of_speech: "noun", definition: "A person who teaches.", example: "My teacher inspired me.", register: "conversational" },
        Definition { word: "watch", part_of_speech: "verb", definition: "To look at attentively.", example: "Watch the movie with me.", register: "conversational" },
        Definition { word: "such", part_of_speech: "determiner", definition: "Of that kind; like that.", example: "Such a beautiful day!", register: "conversational" },
        Definition { word: "since", part_of_speech: "preposition", definition: "From a past time until now.", example: "I have known her since childhood.", register: "conversational" },
        Definition { word: "ever", part_of_speech: "adverb", definition: "At any time.", example: "Have you ever been to Paris?", register: "conversational" },
        Definition { word: "different", part_of_speech: "adjective", definition: "Not the same as another.", example: "We have different opinions.", register: "conversational" },
        Definition { word: "possible", part_of_speech: "adjective", definition: "Able to be done or achieved.", example: "Anything is possible if you try.", register: "conversational" },
        Definition { word: "matter", part_of_speech: "noun", definition: "An affair or situation.", example: "It doesn't matter.", register: "conversational" },
        Definition { word: "music", part_of_speech: "noun", definition: "Vocal or instrumental sounds.", example: "Music soothes the soul.", register: "literary" },
        Definition { word: "picture", part_of_speech: "noun", definition: "A visual representation.", example: "Take a picture of the sunset.", register: "conversational" },
        Definition { word: "game", part_of_speech: "noun", definition: "An activity for amusement.", example: "Let's play a game.", register: "conversational" },
        Definition { word: "street", part_of_speech: "noun", definition: "A public road in a city.", example: "The street was quiet at night.", register: "conversational" },
        Definition { word: "hour", part_of_speech: "noun", definition: "A unit of time equal to 60 minutes.", example: "I waited for an hour.", register: "conversational" },
        Definition { word: "bring", part_of_speech: "verb", definition: "To carry or convey.", example: "Bring an umbrella, it might rain.", register: "conversational" },
        Definition { word: "leave", part_of_speech: "verb", definition: "To go away from.", example: "Don't leave me alone.", register: "conversational" },
        Definition { word: "white", part_of_speech: "adjective", definition: "Of the color of snow.", example: "A white dove flew overhead.", register: "conversational" },
        Definition { word: "black", part_of_speech: "adjective", definition: "Of the darkest color.", example: "She wore a black dress.", register: "conversational" },
        Definition { word: "red", part_of_speech: "adjective", definition: "Of the color of blood.", example: "The red rose symbolizes love.", register: "literary" },
        Definition { word: "blue", part_of_speech: "adjective", definition: "Of the color of the sky.", example: "The sky is blue today.", register: "conversational" },
        Definition { word: "green", part_of_speech: "adjective", definition: "Of the color of grass.", example: "The green fields stretched for miles.", register: "conversational" },
        Definition { word: "best", part_of_speech: "adjective", definition: "Of the most excellent quality.", example: "She is my best friend.", register: "conversational" },
        Definition { word: "better", part_of_speech: "adjective", definition: "Comparative of good.", example: "I feel better today.", register: "conversational" },
        Definition { word: "table", part_of_speech: "noun", definition: "A piece of furniture with a flat top.", example: "Put the plates on the table.", register: "conversational" },
        Definition { word: "clear", part_of_speech: "adjective", definition: "Easy to see through or understand.", example: "The instructions were clear.", register: "conversational" },
        Definition { word: "reason", part_of_speech: "noun", definition: "A cause or explanation.", example: "Tell me the reason.", register: "conversational" },
        Definition { word: "build", part_of_speech: "verb", definition: "To construct something.", example: "They will build a new school.", register: "conversational" },
        Definition { word: "late", part_of_speech: "adjective", definition: "After the expected time.", example: "Don't be late for class.", register: "conversational" },
        Definition { word: "tree", part_of_speech: "noun", definition: "A perennial plant with a trunk.", example: "The tree provides shade.", register: "conversational" },
        Definition { word: "short", part_of_speech: "adjective", definition: "Of small length or duration.", example: "The movie was short.", register: "conversational" },
        Definition { word: "force", part_of_speech: "noun", definition: "Strength or energy exerted.", example: "The force of the wind knocked the tree over.", register: "conversational" },
        Definition { word: "ready", part_of_speech: "adjective", definition: "Prepared for action or use.", example: "Are you ready to go?", register: "conversational" },
        Definition { word: "road", part_of_speech: "noun", definition: "A path for vehicles.", example: "The road leads to the beach.", register: "conversational" },
        Definition { word: "listen", part_of_speech: "verb", definition: "To give attention to sound.", example: "Listen carefully to the teacher.", register: "conversational" },
        Definition { word: "simple", part_of_speech: "adjective", definition: "Easily understood or done.", example: "It's a simple recipe.", register: "conversational" },
        Definition { word: "language", part_of_speech: "noun", definition: "A system of communication.", example: "Learning a new language is rewarding.", register: "conversational" },
        Definition { word: "member", part_of_speech: "noun", definition: "A person belonging to a group.", example: "She is a member of the club.", register: "conversational" },
        Definition { word: "past", part_of_speech: "noun", definition: "The time before the present.", example: "Learn from the past.", register: "conversational" },
        Definition { word: "term", part_of_speech: "noun", definition: "A word or phrase for a thing.", example: "What does this term mean?", register: "conversational" },
        Definition { word: "whole", part_of_speech: "adjective", definition: "All of something; entire.", example: "I ate the whole pizza.", register: "conversational" },
        Definition { word: "wait", part_of_speech: "verb", definition: "To remain in readiness.", example: "Wait for me!", register: "conversational" },
        Definition { word: "figure", part_of_speech: "noun", definition: "A shape or number.", example: "The figure was tall and mysterious.", register: "literary" },
        Definition { word: "set", part_of_speech: "noun", definition: "A group of items.", example: "A set of keys.", register: "conversational" },
        Definition { word: "gun", part_of_speech: "noun", definition: "A weapon that fires bullets.", example: "The police officer carried a gun.", register: "conversational" },
    ]
}